name: EarthScope
title: fetch-scripts - command line access to seismic data
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-relative-links
relative_links:
  enabled:     true
  collections: false
